name: PersonalAgent
options:
  bundleIdPrefix: com.personalagent
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic

packages:
  SwiftTerm:
    url: https://github.com/migueldeicaza/SwiftTerm.git
    from: "1.2.0"

targets:
  PersonalAgent:
    type: application
    platform: iOS
    sources:
      - path: Sources
        excludes:
          - "**/.DS_Store"
    dependencies:
      - package: SwiftTerm
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.personalagent.app
        INFOPLIST_FILE: Sources/App/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_PREVIEWS: true
    info:
      path: Sources/App/Info.plist
      properties:
        CFBundleDisplayName: Personal Agent
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        UILaunchScreen:
          UIColorName: LaunchBackground
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSCameraUsageDescription: "Personal Agent uses the camera to scan QR codes for quick pairing with your Mac."
        NSMicrophoneUsageDescription: "Personal Agent uses the microphone for voice input to control your terminal sessions."
        NSSpeechRecognitionUsageDescription: "Personal Agent uses speech recognition to transcribe your voice commands."
        NSLocalNetworkUsageDescription: "Personal Agent connects to your Mac Mini over your local network via Tailscale."
        NSAppTransportSecurity:
          NSAllowsLocalNetworking: true
          NSAllowsArbitraryLoads: true
        UIBackgroundModes:
          - audio
    entitlements:
      path: Sources/App/PersonalAgent.entitlements
      properties:
        com.apple.security.network.client: true
